linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - deadcode
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: "(.+)_test.go"
      linters:
        - goerr113
        - forcetypeassert
        - wrapcheck
        - varnamelen
    - linters:
        - wrapcheck
      text: ".*labstack/echo/v4\\.Context.*"
linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
  lll:
    line-length: 150
