name: build

on:
  pull_request:
    branches: 
      - main

concurrency:
  group: build-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      uses: goreleaser/goreleaser-action@v2.8.1
      with:
        version: latest
        args: release --snapshot --skip-validate --skip-publish
      env:
        GITHUB_TOKEN: ${{ secrets.INTEGRATION_TOKEN }}