name: lint
on:
  pull_request:
concurrency:
  group: golint-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: "Get GOROOT"
        id: goroot
        run: |
          echo ::set-output name=GOROOT?::${GOROOT}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m0s --verbose --out-${NO_FUTURE}format colored-line-number
          version: v1.48.0
        env:
          GOROOT: ${{ steps.goroot.outputs.GOROOT }}
