name: Lint Golang
on:
  pull_request:
concurrency:
  group: golint-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: "Set GOROOT"
        run: |
          # Explicitly set GOROOT to avoid golangci-lint/issues/3107
          export "GOROOT=$(go env GOROOT)"
        shell: bash          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m0s --verbose --out-${NO_FUTURE}format colored-line-number
          version: v1.47.2
